### ISSUE TITLE
eaa update command doesn't work

### ISSUE THREAD

**Issue by thayakaw** [akamai/cli-eaa#41]
When using "cat xxx.json | akamai eaa app app://abcdefg update" command, following error is seen.
Customer insists **they can update successfully with same command in the version of 0.5.6**, but I can't test it.
Can you please confirm the behavior of it?

[eaa version: 0.6.3]
2024-04-26 17:02:26,242 root E cli-eaa general exception
Traceback (most recent call last):
  File "/Users/thayakaw/.akamai-cli/src/cli-eaa/bin/akamai-eaa", line 274, in <module>
    a.process_command()
  File "/Users/thayakaw/.akamai-cli/src/cli-eaa/libeaa/application.py", line 120, in process_command
    self.update(app, new_config)
  File "/Users/thayakaw/.akamai-cli/src/cli-eaa/libeaa/application.py", line 445, in update
    postjj_app_config = self.parse_template(raw_app_config)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thayakaw/.akamai-cli/src/cli-eaa/libeaa/application.py", line 273, in parse_template
    output = t.render(**dict(self._config.variables))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

[eaa version: 0.6.6]
2024-04-26 17:26:01,499 root E cli-eaa general exception
Traceback (most recent call last):
  File "/Users/thayakaw/.akamai-cli/src/cli-eaa/bin/akamai-eaa", line 311, in <module>
    a.process_command()
  File "/Users/thayakaw/.akamai-cli/src/cli-eaa/libeaa/application.py", line 121, in process_command
    self.update(app, new_config)
  File "/Users/thayakaw/.akamai-cli/src/cli-eaa/libeaa/application.py", line 450, in update
    postjj_app_config = self.parse_template(raw_app_config)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thayakaw/.akamai-cli/src/cli-eaa/libeaa/application.py", line 276, in parse_template
    output = t.render(**dict(self._config.variables))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable

**Comment by thayakaw** [comment]
Hi @bitonio,
This is an inquiry from our lighthouse EAA account. Can you please confirm it?

**Comment by bitonio** [comment]
That's a regression, I fixed it and will push an new version with a fix very soon.

**Comment by thayakaw** [comment]
Thanks. I'll be very helpful. Please let me know once you complete the fix.
