### ISSUE TITLE
Akamai EAA API Connection error

### ISSUE THREAD

**Issue by rahul8172q** [akamai/cli-eaa#7]
I am running the urls API code ,  akamai eaa --edgerc /Users/XXXX/.edgerc log --start 1627984800 --end 1627999200  | grep "APP_NAME"  | awk '{print $1,$2,$3,$25}' but its failing sometime after 1 hr and sometimes after 6 hrs. So, random times with below error.

Traceback (most recent call last):
  File "/Users/.akamai-cli/src/cli-eaa/lib/python/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/.akamai-cli/src/cli-eaa/lib/python/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/.akamai-cli/src/cli-eaa/lib/python/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/.akamai-cli/src/cli-eaa/lib/python/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users//.akamai-cli/src/cli-eaa/lib/python/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/Users/.akamai-cli/src/cli-eaa/lib/python/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/.akamai-cli/src/cli-eaa/lib/python/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/.akamai-cli/src/cli-eaa/lib/python/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users//.akamai-cli/src/cli-eaa/lib/python/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users//.akamai-cli/src/cli-eaa/lib/python/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/.akamai-cli/src/cli-eaa/libeaa/eventlog.py", line 104, in get_logs
    resp = self.post(self.get_api_url(logtype, logversion), json=drpc_args)
  File "/Users/.akamai-cli/src/cli-eaa/libeaa/common.py", line 239, in post
    response = self._session.post(url, json=json, params=self.build_params(params), timeout=HTTP_REQ_TIMEOUT)
  File "/Users//.akamai-cli/src/cli-eaa/lib/python/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users//.akamai-cli/src/cli-eaa/lib/python/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users//.akamai-cli/src/cli-eaa/lib/python/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/.akamai-cli/src/cli-eaa/lib/python/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

**Comment by bitonio** [comment]
Hi,

Thanks for sharing the detailed error.

According to the exception, it looks like the reset is initiated on the server side, I'll have a look.
I'd consider to fetch smaller segment of time like 15 minutes, see if that helps.

Have you consider also our Unified Log Streamer (https://github.com/akamai/uls), it wraps cli-eaa and comes with retry mechanism. It is designed to send the data to a SIEM over UDP/TCP/HTTP.

I'll update this ticket with my finding.

**Comment by rahul8172q** [comment]
Yeah.. I tried smaller segments and it worked well but I need data for connection an a specific app for 2 months( can break for 15 days in multiple chunks)

also, I tried ULS as well but I am getting live data and not past data. If I am doing something wrong, will you point me in the right direction.
 python3 bin/uls.py -i EAA --edgerc /Users/XXXX/.edgerc -o RAW --filter '.*"apphost": "<<APPNAME>>".*'

I need past data, how can I add a filter or START and END date

**Comment by bitonio** [comment]
Thanks for sharing more background. We send the log date range directly to the underlying API which has a pagination mechanism. We receive 1000 results, and iterate if their is more data. Each iteration is a new HTTP POST request so with a wide range or a lot of log event you end up with lots of requests. For optimal performance, we rely on connection pooling. The pooling library comes with retry mechanism but won't retry when a `ConnectionResetError` is raised with a POST request.

I am looking at some elegant way to introduce a retry (as the POST request in question is idempotent) also when this type of exception occurs to improve overall reliability. 

In the meantime, if you are calling `cli-eaa` from a shell, I'd script a split the full range of time (like 2 months) into small chunks to achieve what you're looking for.

I am working on a small bugfix right now and should have something ready by end of this week, I'll tentatively add a change to better accommodate this error.

**Comment by rahul8172q** [comment]
you mean by using uls.py or akamai, i should script?
When i use /bin/uls.py, it gives me live logs rather than old logs.

i can script using akamai eaa but it sometime crashes after 3 hrs , 2hrs and quite randomly.

i can try but can wait  as well, if there is something that can help me.

**Comment by bitonio** [comment]
I meant `akamai eaa`.
You're correct, uls doesn't fit your use case.

You may check the return code of the `akamai eaa` command, if not 0, it means the command has failed and you may retry. I have made some progress since my last comment 35 minutes ago, I might be able to ship a fix by EOD.

**Comment by bitonio** [comment]
@rahul8172q we released 0.4.3 that include a retry mechanism.
It should prevent fatal break on large quantities of logs, yet you may loose some data if the POST request ever got to the server. Overall that should improve the reliability.

I'll leave this ticket open until I hear back from you.

**Comment by rahul8172q** [comment]
Cool. Thanks a mil. I re-ran the command o today and to he below error 
021-09-10 10:27:10,932 root E {'sts': '1627772519000', 'ets': '1630364519000', 'metrics': 'logs', 'es_fields': 'flog', **'limit': '1000', '**sub_metrics': 'scroll', 'source': 'akamai-cli/eaa',
2021-09-10 10:27:10,935 root E Exception in get_logs
Traceback (most recent call last):
  File "/Users/xxxxx/.akamai-cli/src/cli-eaa/libeaa/eventlog.py", line 124, in get_logs
    resj = resp.json()
  File "/Users/xxxx/.akamai-cli/src/cli-eaa/lib/python/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by bitonio** [comment]
Thanks for the new tentative. 

It seems to be a network error that triggers after receiving the first few bytes (like just headers), yet you don't get the full response causing the JSON parser to fail.

While I could trigger a retry on JSON parsing failure, this will cause data loss and the remove server will serve you the next page.

I have some other ideas outside the CLI that could work, I would need a few days.
Given that's a network issue and not CLI related, I'll close this GH ticket and we can continue over email, you can reach me at androcho (at) akamai (d0t) com

Thanks for you patience!

**Comment by rahul8172q** [comment]
Sure . Thanks a lot. I will try . Will reach out , if need help.

**Comment by bitonio** [comment]
I manage to get something you can try.
In your `.edgerc` file, replace the line:
```
eaa_api_host = manage.akamai-access.com
```
by
```
eaa_api_host = manage-akamai-access-com.zerotrust.rocks
```

Let me know if that works better.

**Comment by rahul8172q** [comment]
That , gave me a connection error.


Thanks
Rahul Misra

**Comment by bitonio** [comment]
> That , gave me a connection error.
Could you share some details, like using the cli with `-d` or `-v`
This is an example with `-v`:
```
% akamai eaa -v log --start 1627984800 --end 1627999200 --output ~/tmp/issue_7.log
2021-09-13 11:10:55,611 root I Initialized with base_url https://manage-akamai-access-com.zerotrust.rocks/api/v1/
2021-09-13 11:10:55,612 root I EventType.USER_ACCESS
2021-09-13 11:10:55,612 root I PID: 22775
2021-09-13 11:10:55,612 root I Poll interval: 15 seconds
2021-09-13 11:10:55,612 root I Output file: /Users/androcho/tmp/issue_7.log
2021-09-13 11:10:55,613 root I Fetching log[EventType.USER_ACCESS] from 1627984800000 to 1627999200000...
2021-09-13 11:10:55,613 root I API URL: https://manage-akamai-access-com.zerotrust.rocks/api/v1/analytics/ops-data
2021-09-13 11:10:56,868 root I BaseAPI: POST response is HTTP 200
2021-09-13 11:10:56,892 root I API URL: https://manage-akamai-access-com.zerotrust.rocks/api/v1/analytics/ops-data
2021-09-13 11:10:57,182 root I BaseAPI: POST response is HTTP 200
2021-09-13 11:10:57,205 root I API URL: https://manage-akamai-access-com.zerotrust.rocks/api/v1/analytics/ops-data
2021-09-13 11:10:57,428 root I BaseAPI: POST response is HTTP 200
2021-09-13 11:10:57,452 root I API URL: https://manage-akamai-access-com.zerotrust.rocks/api/v1/analytics/ops-data
2021-09-13 11:10:57,725 root I BaseAPI: POST response is HTTP 200
2021-09-13 11:10:57,748 root I API URL: https://manage-akamai-access-com.zerotrust.rocks/api/v1/analytics/ops-data
2021-09-13 11:10:57,955 root I BaseAPI: POST response is HTTP 200
2021-09-13 11:10:57,979 root I API URL: https://manage-akamai-access-com.zerotrust.rocks/api/v1/analytics/ops-data
2021-09-13 11:10:58,199 root I BaseAPI: POST response is HTTP 200
2021-09-13 11:10:58,223 root I API URL: https://manage-akamai-access-com.zerotrust.rocks/api/v1/analytics/ops-data
2021-09-13 11:10:58,425 root I BaseAPI: POST response is HTTP 200
2021-09-13 11:10:58,448 root I API URL: https://manage-akamai-access-com.zerotrust.rocks/api/v1/analytics/ops-data
2021-09-13 11:10:58,551 root I BaseAPI: POST response is HTTP 200
2021-09-13 11:10:58,557 root I API URL: https://manage-akamai-access-com.zerotrust.rocks/api/v1/analytics/ops-data
2021-09-13 11:10:58,613 root I BaseAPI: POST response is HTTP 200
# Start: 08/03/2021 10:00:00 UTC (EPOCH 1627984800)
# End: 08/03/2021 14:00:00 UTC (EPOCH 1627999200)
# Total: 7219 event(s), 0 error(s), 2946845 bytes written
2021-09-13 11:10:58,613 root I 7219 log lines were fetched.
```

**Comment by rahul8172q** [comment]
Hey Antoine,

Please find the result:

uls % akamai eaa -v --edgerc /Users/xxxx/.edgerc log --start 1627772519
--end 1630364519  | awk '{print $1,$2,$3,$25}' >>
/Users/xxxx/Downloads/1stAug-31Aug2.txt

2021-09-13 20:13:11,542 root I Initialized with base_url
https://manage.akamai-access.com.zerotrust.rocks/api/v1/
2021-09-13 20:13:11,543 root I EventType.USER_ACCESS
2021-09-13 20:13:11,543 root I PID: 45359
2021-09-13 20:13:11,543 root I Poll interval: 15 seconds
2021-09-13 20:13:11,543 root I Fetching log[EventType.USER_ACCESS] from
1627772519000 to 1630364519000...
2021-09-13 20:13:11,543 root I API URL:
https://manage.akamai-access.com.zerotrust.rocks/api/v1/analytics/ops-data
2021-09-13 20:13:11,603 root W ConnectionError, retry left: 4
2021-09-13 20:13:12,609 root I API URL:
https://manage.akamai-access.com.zerotrust.rocks/api/v1/analytics/ops-data
2021-09-13 20:13:12,613 root W ConnectionError, retry left: 3
2021-09-13 20:13:13,618 root I API URL:
https://manage.akamai-access.com.zerotrust.rocks/api/v1/analytics/ops-data
2021-09-13 20:13:13,623 root W ConnectionError, retry left: 2
2021-09-13 20:13:14,624 root I API URL:
https://manage.akamai-access.com.zerotrust.rocks/api/v1/analytics/ops-data
2021-09-13 20:13:14,628 root W ConnectionError, retry left: 1
2021-09-13 20:13:15,632 root I API URL:
https://manage.akamai-access.com.zerotrust.rocks/api/v1/analytics/ops-data
2021-09-13 20:13:15,636 root W ConnectionError, retry left: 0
2021-09-13 20:13:16,640 root E {'sts': '1627772519000', 'ets':
'1630364519000', 'metrics': 'logs', 'es_fields': 'flog', 'limit': '1000',
'sub_metrics': 'scroll', 'source': 'akamai-cli/eaa'}
2021-09-13 20:13:16,640 root E Exception in get_logs
Traceback (most recent call last):
  File
"/Users/xxxxx/.akamai-cli/src/cli-eaa/lib/python/site-packages/urllib3/connection.py",
line 169, in _new_conn
    conn = connection.create_connection(
  File
"/Users/xxxx/.akamai-cli/src/cli-eaa/lib/python/site-packages/urllib3/util/connection.py",
line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File ***@***.***/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py",
line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File
"/Users/xxxxx/.akamai-cli/src/cli-eaa/lib/python/site-packages/urllib3/connectionpool.py",
line 699, in urlopen
    httplib_response = self._make_request(
  File
"/Users/xxxxx/.akamai-cli/src/cli-eaa/lib/python/site-packages/urllib3/connectionpool.py",
line 382, in _make_request
    self._validate_conn(conn)
  File
"/Users/xxxx/.akamai-cli/src/cli-eaa/lib/python/site-packages/urllib3/connectionpool.py",
line 1010, in _validate_conn
    conn.connect()
  File
"/Users/xxxxx/.akamai-cli/src/cli-eaa/lib/python/site-packages/urllib3/connection.py",
line 353, in connect
    conn = self._new_conn()
  File
"/Users/xxxxx/.akamai-cli/src/cli-eaa/lib/python/site-packages/urllib3/connection.py",
line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection
object at 0x106bc9bb0>: Failed to establish a new connection: [Errno 8]
nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File
"/Users/xxxx/.akamai-cli/src/cli-eaa/lib/python/site-packages/requests/adapters.py",
line 439, in send
    resp = conn.urlopen(
  File
"/Users/xxxxx/.akamai-cli/src/cli-eaa/lib/python/site-packages/urllib3/connectionpool.py",
line 755, in urlopen
    retries = retries.increment(
  File
"/Users/xxxxx/.akamai-cli/src/cli-eaa/lib/python/site-packages/urllib3/util/retry.py",
line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='
http://manage.akamai-access.com.zerotrust.rocks', port=443): Max retries
exceeded with url: /api/v1/analytics/ops-data (Caused by
NewConnectionError('<urllib3.connection.HTTPSConnection object at
0x106bc9bb0>: Failed to establish a new connection: [Errno 8] nodename nor
servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xxxx/.akamai-cli/src/cli-eaa/libeaa/eventlog.py", line 112,
in get_logs
    resp = self.post(self.get_api_url(logtype, logversion), json=drpc_args)
  File "/Users/xxxx/.akamai-cli/src/cli-eaa/libeaa/common.py", line 239, in
post
    response = self._session.post(url, json=json,
params=self.build_params(params), timeout=HTTP_REQ_TIMEOUT)
  File
"/Users/xxxx/.akamai-cli/src/cli-eaa/lib/python/site-packages/requests/sessions.py",
line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File
"/Users/xxxx/.akamai-cli/src/cli-eaa/lib/python/site-packages/requests/sessions.py",
line 542, in request
    resp = self.send(prep, **send_kwargs)
  File
"/Users/xxxx/.akamai-cli/src/cli-eaa/lib/python/site-packages/requests/sessions.py",
line 655, in send
    r = adapter.send(request, **kwargs)
  File
"/Users/xxxx/.akamai-cli/src/cli-eaa/lib/python/site-packages/requests/adapters.py",
line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='
http://manage.akamai-access.com.zerotrust.rocks', port=443): Max retries
exceeded with url: /api/v1/analytics/ops-data (Caused by
NewConnectionError('<urllib3.connection.HTTPSConnection object at
0x106bc9bb0>: Failed to establish a new connection: [Errno 8] nodename nor
servname provided, or not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xxxx/.akamai-cli/src/cli-eaa/libeaa/eventlog.py", line 118,
in get_logs
    raise RetryError(f"Give up fetching log after {POST_RETRY_MAX}
retries.")
requests.exceptions.RetryError: Give up fetching log after 5 retries.
2021-09-13 20:13:16,652 root I 0 log lines were fetched.


Thanks
Rahul Misra

**Comment by rahul8172q** [comment]
This is the error. It crashed.

2021-09-14 10:58:42,355 root I API URL:
https://manage-akamai-access-com.zerotrust.rocks/api/v1/analytics/ops-data
2021-09-14 10:58:43,098 root I BaseAPI: POST response is HTTP 200
2021-09-14 10:58:43,115 root I API URL:
https://manage-akamai-access-com.zerotrust.rocks/api/v1/analytics/ops-data
2021-09-14 10:58:43,871 root I BaseAPI: POST response is HTTP 200
2021-09-14 10:58:43,891 root I API URL:
https://manage-akamai-access-com.zerotrust.rocks/api/v1/analytics/ops-data
2021-09-14 10:58:44,475 root I BaseAPI: POST response is HTTP 200
2021-09-14 10:58:44,494 root I API URL:
https://manage-akamai-access-com.zerotrust.rocks/api/v1/analytics/ops-data
2021-09-14 10:58:45,062 root I BaseAPI: POST response is HTTP 200
2021-09-14 10:58:45,062 root E {'sts': '1627772519000', 'ets':
'1630364519000', 'metrics': 'logs', 'es_fields': 'flog', 'limit': '1000',
'sub_metrics': 'scroll', 'source': 'akamai-cli/eaa', 'scroll_id': '

021-09-14 10:58:45,063 root E Exception in get_logs
Traceback (most recent call last):
  File "/Users/xxxx/.akamai-cli/src/cli-eaa/libeaa/eventlog.py", line 124,
in get_logs
    resj = resp.json()
  File
"/Users/xxxx/.akamai-cli/src/cli-eaa/lib/python/site-packages/requests/models.py",
line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File ***@***.***/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py",
line 346, in loads
    return _default_decoder.decode(s)
  File ***@***.***/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py",
line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File ***@***.***/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py",
line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 3 (char 2)
2021-09-14 10:58:45,067 root I 837000 log lines were fetched.

Thanks
Rahul Misra
